lua.lua

Add lua Hello World

---

bash.sh

https://github.com/knightking100/hello-worlds/issues/1

Add bash Hello World

---

python.py

Add python Hello World

---

Java.java

Add Java Hello World

---

Delphi.dpr
Java.java

Add Delphi Hello World

---

Ruby.rb

Add Ruby Hello World

---

typescript.ts

Add typescript Hello World

---

zsh.sh

Add zsh Hello World

---

C.c

Add C Hello World

---

Elixir..exs

Add Elixir Hello World

---

Elixir..exs

Revert "Add Elixir Hello World"

---

coffeescript.coffee

Add coffeescript Hello World

---

Scala.scala

Add Scala Hello World

---

Go.go

Add Go Hello World

---

Haskell.hs

Add Haskell Hello World

---

tex.tex

Add Tex Hello World

---

ksh.sh

Add Korn Shell Hello World

---

awk.awk

Add awk Hello World

---

Javascript.js

Add Javascript Hello World

---

Groovy.gsh
JavaScript.js

Add Groovy Hello World

---

AppleScript.scpt
cobra.cobra

#1 Add AppleScript Hello World

Add Cobra Hello World

---

AppleScript.scpt

#1 Add AppleScript Hello World

Add AppleScript Hello World

---

cobol.cob

Add COBOL Hello World

---

Pascal.pas

Add Pascal Hello World

---

FSharp.fs

Add F# Hello World

---

php.php

Add PHP Hello World

---

Lisp.lisp

Add Lisp Hello World

---

plsql.sql

Add PL/SQL Hello World

---

Visual Basic NET.vb

Add Visual Basic .NET Hello World

---

kotlin.kt

Add Kotlin Hello World

---

Dart.dart

Add Dart Hello World

---

Rust.rs

Add Rust Hello World

---

Fortran.f95

Add Fortran Hello World

---

MoonScript.moon

NOTE: [MoonScript](http://moonscript.org) is not listed in #1 .-.
Pls Add the list :) Thank

Add MoonScript Hello World

---

R.R

Add R Hello World

---

arduino.ino

Addresses issue #1 
- This PR adds `Hello World` program in Arduino language. 👍

Add Arduino Hello World

---

erlang.erl

Add Erlang Hello World

---

ActionScript.as

Add ActionScript Hello World

---

sml.sml

Add  Standard ML

---

php.php

Updated php.php

---

C#.cs

Add C# Hello World

---

Clojure.clj

Add clojure

---

MS-DOS_Batch.bat

Add MS-DOS Batch Hello World.

---

c++_cli.cpp

Add C++/CLI Hello World.

---

D.d

Add D Hello World.

---

io.io

Add io Hello World

---

Cshell.csh

Add C Shell Hello World

---

boo.boo

Add Boo Hello World

---

SAS.sas

Hello world in SAS
https://github.com/knightking100/hello-worlds/issues/1

Add SAS.sas

---

GoogleAppsScript.gs

GoogleAppsScript Hello World Email Document

---

Ti-z80.83p

Added Ti-z80 Basic.

---

Scheme.scm

Add a hello world program written in Scheme.

Add Scheme.scm

---

fish.fish

Add Fish Shell Hello World

---

coldfusion.cfm

Added ColdFusion.cfm

---

swift.swift

Please update the list. The Swift language is missing in #1.

Add Swift Hello World

---

REBOL.r
Racket.rkt

Added Hello World Code for Racket Programming Language.

Add Racket.rkt

---

idris.idr

Hello world in Idris lang. 
Ref #1 and #131.

Added idris.idr

---

HAI _WORLD.lol
racket.rkt

Added Hello World in LOLCODE
HAI_WORLD.lol

Added Hello World in LOLCODE & Racket

---

processing.pde

Add Processing Hello World

---

crystal.cr

Add Crystal Hello World

---

Pseudocode.txt

Created 'Hello World' for Pseudocode

---

verilog.v

Adds verilog.v

---

Turing.t

Adds Turing.t

---

Parrot.pir

Adds Parrot.pir

---

Euphoria.ew

Adds Euphoria.ew

---

fortress.fss

Add Fortress Hello World

---

Factor.factor

Add Factor hello world

---

BCPL.bcpl

Add BCPL Hello World

---

nu.nu

Add nu Hello World

---

icon.icn

Added icon.icn

---

lasso.lasso

Added Hello World file for Lasso Programming language

---

css.css

Add CSS Hello World

---

AutoHotkey.ahk
prolog.pl

Add hello world in AutoHotkey

---

caml.ml

Hi,
Just added *Hello world!* in Caml. #1

Added Caml Hello World

---

Objective_J.j

Add Objective-J hello world

---

M4.m4

Related to #1. Assuming that M4 refers to the general-purpose macro processor.

Add M4 hello world

---

PHP.php

- Changed double to single quotes
- Omitted the PHP closing tag

Refactoring code within PHP.php

---

ShakespeareProgrammingLanguage.spl

Add Shakespeare Programming Language Hello World  

---

examples/VHDL.vhd
examples/VimScript.vim

Add VimScript Hello World. References #1

Add VimScript Hello World

---

examples/VimScript.vim

Actual VimScript Hello World :)

Added VimScript Hello World

---

examples/ballerina.bal

Related to #1. 
This code block is developed in [ballerina](https://ballerinalang.org/) 0.93.

Add helloWorld in ballerina

---

LANGUAGES.md
examples/mysql.sql

Adding MySQL hello world

---

examples/slow_hello_world.py

Thought we should have some variety, print hello world letter by letter onto CMD

slow_hello_world.py

---

examples/JADE.jade

#1 
I have added 'Hello world' in JADE language

Added Hello world in JADE language to the repo

---

examples/Clean.clean
examples/JADE.jade
examples/Lily.lily
examples/kitten.cat

#1
Added 'Hello World' in kitten and Clean languages.

Complete for kitten and Clean languages

---

examples/Idl.idl

Add IDL Hello worlds

---

examples/Gentee.g

Add Gentee Hello World

---

examples/java_(3).java
examples/java_3.java

##Added Hello World Java Program

Added Helloworld program of Java Language

---

examples/KonsolScript.konsl

KonsolScript example

---

examples/Ansible.yaml

Added Ansible.yaml
Reference: https://github.com/knightking100/hello-worlds/issues/1

Added Ansible.yaml

---

examples/Elm.elm

HelloWorld elm

---

examples/xslt.xml
examples/xslt.xsl

#1 XSLT "Hello World" Example implemented

#1 Added Hello World in XSLT

---

examples/amiga-E

Added new hello world in Amiga-E language

Amiga-E Hello World

---

Java_6.java

Created Java_6.java

---

LANGUAGES.md
examples/A+

Add A+ lang

---

examples/Bro.bro

Added 'Hello World' for Bro language

---

examples/JCL.jcl

Added Hello world in JCL language

Added Hello world in JCL language

---

examples/PHP_3.php

Created PHP_3.php

---

examples/C_4.c

Added C_4: C Hello World without any header

---

examples/MIRC.mrc

For issue #1
Usage:
/load -rsN C:\Users\myuser\Download\MIRC.mrc
/hello

Add MIRC hello world!

---

Golfscript.gs

Hey,
Just added _Hello World!_ in Golfscript. #1

Added Golfscript Hello World

---

examples/hello.tr

TrumpScript is the best language, only hello world program you ever need
to have. For more information on how great it is to use, check out the
repository here: https://github.com/samshadwell/TrumpScript
(I figure if you've got brainfuck, why not TS?)

Add Hello World in TrumpScript

---

examples/Logo.LOGO

Created Logo.LOGO

---

examples/Vala.vala

Hello World in Vala

---

examples/Hodor.hd

Reference Issue [#1](https://github.com/knightking100/hello-worlds/issues/1)
To run from the CLI:
1. npm install -g hodor-lang
2. hodor Hodor.hd
You can view Hodor documentation [here](https://github.com/hummingbirdtech/hodor).

added Hello World example for hodor-lang

---

examples/fortran90.f90

=) 
Still missing the fortran 77 version

Added a fortran90 version of Hello World

---

examples/JavaScript_6.js

Add react hello world file

---

LANGUAGES.md
examples/AntScript.xml

#1 
See https://ant.apache.org/

Ant Script

---

examples/Java_7.java

Java "Hello World!" example with `\u000d`.

Example with unicode newline character.

---

examples/Dogescript.djs
examples/Hy.hy

Add hylang

---

examples/Xlisp.lsp

added Xlisp

---

examples/Scilab.sci

Add Scilab

---

examples/Zombie.z

Add Zombie language Hello world

---

LANGUAGES.md
examples/VisualFoxPro.prg

Hi,
Nice collection and I'd like to add Microsoft Visual FoxPro (VFP) to it. Thanks!

add Visual FoxPro incl. sample program

---

examples/Suicide.suicide

Issue [#1](https://github.com/knightking100/hello-worlds/issues/1)

Added Hello World for Suicide

---

examples/Owl.owl

Can be executed from a cli with $owl Owl.owl

Added hellow world in owl

---

examples/HTML_3.html
examples/HTML_4.html

HTML_3.html

---

examples/AntLang.ant

Added hello world in AntLang

---

examples/Ring.ring

This pull request is for the issue no. #1
I made sure that before opening this pull request I have starred this repo

Added Hello World in Ring Language

---

examples/QBasic.bas

Added Hello World in QBasic

---

examples/Alore.alo

added hello world in Alore

---

PhilosophyScript.PhS

ISSUE #1 
Added a file that contains the code to print "Hello, world" to the output screen using the Philosophy Script language.

This is the Hello World program for the Philosophy Script language.

---

examples/OOLANG.obj

Addresses #1
Tested using interpreter http://alc.comuf.com/oolang.php from http://esolangs.org/wiki/OOLANG

OOLANG Hello world program

---

examples/Paintfuck.pf

#1
Prints Hello World in the center of the interpreter.
Language reference http://esolangs.org/wiki/Paintfuck
Interpreter reference http://www.formauri.es/personal/pgimeno/temp/esoteric/paintfuck/paintfuck-canvas.php

Paintfuck "HELLO WORLD!" program

---

examples/Ook!.txt

Added Hello World in Ook!

---

examples/JavaScript_9.js

Ouput "Hello World" from charcode

Added Javascript "Hello World" from charcode

---

examples/foo.foo

Adding foo language Hello World

---

examples/Fetlang.fet

Add one of the languages (fetlang in this case) listed in #1

Add "Hello world" for the Fetlang language.

---

examples/X10.x10

In reference to issue #1 , Added a file X10.x10 which prints `Hello, World!` in X10 programming language.

Added hello world file in X10 language, reference issue #1

---

examples/7Basic.b

Added 7Basic

---

examples/Java_9.java

update changes 

---

examples/chicken.chicken

Added Hello World in chicken

---

examples/Hello_php_script.php

added a php script of hello world !

New Hello World Program in php

---

examples/SwiftHelloWorld.playground/elixir2.ex

with two anonymous functions and pipe operator

added more interesting Elixir example 

---

examples/Latino.lat

"Hello World!" in [Latino](http://lenguaje-latino.org/)

Add "Hello World!" in Latino

---

LANGUAGES.md
examples/Brightscript.brs

Brightscript is the language for Roku devices.

Add Brightscript example

---

examples/Hello World.vim

hello world program using omgrofl

OMGROFL.vim

---

examples/QBasic.bas
examples/QBasic_2.bas

Update QBasic.bas and add QBasic_2.bas

---

examples/vue.js

Added Hello world in Vue.js

---

examples/ZebraProgrammingLanguage.zpl

Hello world in Zebra programming language.

Hello world in Zebra programming language.

---

LANGUAGES.md
examples/Pikachu

#1 
More info at [The Pikachu Programming Language](http://trove42.com/introducing-pikachu-programming-language/).

Add Hello World in Pikachu

---

examples/Forth.fth

Added hello world for Forth
Issue #1

Forth hello world

---

examples/Pyth.py

Here is a tiny hello world written in Pyth!
#1

Add Pyth hello world

---

examples/05AB1E.abe

Here is a small hello world written in 05AB1E
#1

Add 05AB1E hello world

---

examples/Manufactoria.java

anufactoria example: add Manufactoria example

---

examples/ARM_HelloWorld.s

Assembly was present, but I added ARM with an LCD screen.

Add ARM upload

---

examples/Chicken.chicken

Source: http://torso.me/chicken

Add Hello World program in Chicken lang

---

LANGUAGES.md
examples/sysrpl.s

System RPL

---

examples/Potion.pn

Hello World Potion 

---

examples/Arduino_2.ino
examples/Arduino_Brasilino.ino

Created a new file Arduino_2.ino
The file contains a way of showing Hello World through Serial Monitor.

Added an example of Arduino using Serial Monitor

---

examples/Muriel.muriel

For issue #1 - added Hello World in Muriel

Added Muriel

---

examples/PLSQL.sql

added _SET serveroutput ON_ , otherwise the **hello world** message won't display.

added SET serveroutput ON

---

examples/LikePython.lp

This is [Like, Python](www.staringispolite.com/likepython/)

add Like, Python example

---

examples/CPL.cpl

Please review at your convenience 🌟 
Sources : 
[http://progopedia.com/language/cpl/](url) 
[https://en.wikipedia.org/wiki/CPL_(programming_language)](url)

Combined Programming Language

---

examples/PHP_10.php

As per #1 
"Hello World!" as a PNG image, created with PHP.
File named as `PHP_10.php` to evade the conflict with PR #674

PHP: Hello, World as a image

---

examples/Bash_5.sh

Hello World in Bash without a *Hello World* in command

Hello World without hello world in command

---

examples/Thue.t

For issue #1, added [Thue](https://esolangs.org/wiki/Thue)
Also checked with [this program](https://www.npmjs.com/package/thue), it prints: **Hello World!**

Added Thue

---

examples/mercury.m

misterpart_hello_world_in_mercury

---

examples/Batch.bat

This Batch File prints an ascii art of "Hello World" but with a twist. It will randomly change colors as the user hits space bar.

Added Batch

---

examples/Laravel.php

Laravel deserves a hello world 👍

Added Laravel

---

LANGUAGES.md
examples/s/Solidity.sol

Issue #1 
Add Hello World in Solidity language

Add Hello World in Solidity

---

LANGUAGES.md
examples/l/Ly.ly

For issue #1.
Updated LANGUAGES.md as well.

Added Ly Hello World

---

examples/v/Vowels.vw

As per issue #1 adding Hello World in Vowels esolang.

Added Vowels

---

LANGUAGES.md
examples/b/BinaryLambdaCalculus
examples/b/Binary_lambda_calculus

Hello World in Binary Lambda Calculus

---

LANGUAGES.md
examples/t/Tom.t

Tom Hello World
Reference to issue #1

Tom Hello World

---

LANGUAGES.md
examples/f/Flogscript.wflog

Flogsript Hello World
Reference Issue #1

flogscript hello world

---

LANGUAGES.md
examples/j/Java/JavaSwing.java
examples/s/Squeak.squeak

Squeak hello world
Reference issue #1

Squeak hello world

---

LANGUAGES.md
examples/k/Kitanai.kitanai

Kitanai hello world
Reference Issue #1

Kitanai hello world

---

examples/k/Kotlin_4.kt

added kotlin example 4

---

LANGUAGES.md
examples/h/HaPyLi.hpl

This implements hello world as taken from the [HaPyLi documentation](http://web.archive.org/web/20120711122654/http://hapyli.webs.com/functions.htm).

Add HaPyLi

---

LANGUAGES.md
examples/t/Terraform.tf

https://www.terraform.io/
It's based on [Hashicorp Config Language](https://github.com/hashicorp/hcl)

add terraform example

---

LANGUAGES.md
examples/#/0

add 0(nop^) example

---

LANGUAGES.md
examples/#/6ix

add 6ix example

---

LANGUAGES.md
examples/a/And

add And example

---

LANGUAGES.md
examples/f/FerNANDo

add FerNANDo example

---

LANGUAGES.md
examples/c/Charcoal.cl

Reference #1
Run via python / charcoal see:
https://github.com/somebody1234/Charcoal
`python charcoal Charcoal.cl `

[ADD] example Charcoal

---

LANGUAGES.md
examples/f/Fission

add Fission example

---

examples/#/~ATH.~ATH

This is a silly sort of language used for fun. The language ~ATH is fictional, and is not used professionally. Although, due to the fair amount of useless research I've done on this language, I am fairly certain that it is correct. Thanks for the opportunity and have a lovely day!

Adding hello world for ~ATH

---

LANGUAGES.md
examples/b/BETA.bet

add BETA example

---

LANGUAGES.md
examples/r/ReactJs_hooks.js

Using React hooks, a new hello world is added.

Adds functional component for React JS

---

LANGUAGES.md
examples/a/Aubergine.aub

add Aubergine example

---

examples/c/Calculon

add Calculon example

---

LANGUAGES.md
examples/m/Mouse

add Mouse example

---

LANGUAGES.md
examples/x/Xquery.xqy

#1 - Added 'Hello World' example in XQuery.

add XQuery example

---

LANGUAGES.md
examples/c/CLC-Intercal.clc

I added the Hello World for CLC-INTERCAL, as well as updating the Languages.md file. Please let me know what I need to change (if anything) to ensure this PR is accepted :)

Add CLC-INTERCAL language (not previously created)
